services:
  dispatch:
    container_name: dispatch
    build: .
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "18087:18087"
    volumes:
      - ./config:/config
      - ./.env:/config/.env:ro
